  <!-- modal -->
  <div class="modal fade" id="modalterminos" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-xl" role="document">
          <div class="modal-content">
                <div class="modal-header text-dark">
                    Terminos y condiciones.
                </div>
                <div class="modal-body">
                    <div class="row text-dark">
                        <p>Bienvenido a CyberGroupOn.com</p>
                        <p>Queremos dejar claro que CyberGroupOn.com no es una "plataforma de inversi&oacute;n, plataforma de regalos o plataforma MLM". No aceptamos fondos con fines de inversi&oacute;n. Nuestro enfoque principal es brindar servicios confiables y eficientes para asegurar que su contenido publicitario llegue a la audiencia adecuada.</p>
                        <p><strong>Recomendaciones y Bonificaciones:</strong></p>
                        <p>Recomendar nuestros servicios es completamente opcional. No recomendar resultar&aacute; en la &ldquo;no obtenci&oacute;n de una bonificaci&oacute;n por referencia.&rdquo; Su papel se centra principalmente en administrar sus campa&ntilde;as publicitarias y utilizar nuestros servicios para sus necesidades promocionales. Aunque puede ser elegible para bonificaciones, esto no est&aacute; garantizado. <u>Si est&aacute; aqu&iacute; exclusivamente</u> para promocionar su negocio, tiene un a&ntilde;o completo para hacerlo, despu&eacute;s de lo cual deber&aacute; comprar un paquete para volver a promocionar. Para extender su tiempo de publicidad y bonificaciones, debe traer 3 compras de referencia en los primeros 5 meses de su compra inicial para obtener una bonificaci&oacute;n por recomendarnos.</p>
                        <p><strong>Transparencia y Soporte al Usuario:</strong></p>
                        <p>Valoramos la transparencia y buscamos que nuestros usuarios comprendan completamente nuestra plataforma. Si&eacute;ntase seguro al administrar sus campa&ntilde;as publicitarias dentro de CyberGroupOn.com, sabiendo que estamos comprometidos a brindar servicios excepcionales y apoyar sus objetivos publicitarios.</p>
                        <p><strong>Compromiso con los Negocios Leg&iacute;timos:</strong></p>
                        <p>CyberGroupOn.com se compromete con el negocio leg&iacute;timo de vender espacios publicitarios en l&iacute;nea. Esta empresa cumple totalmente con las regulaciones a nivel mundial y no est&aacute; prohibida en ning&uacute;n pa&iacute;s.</p>
                        <p><strong>Sistema de Participaci&oacute;n en Ingresos:</strong></p>
                        <p>Cuando compra paquetes de publicidad, el costo total se distribuye entre todos los participantes. Este sistema de participaci&oacute;n en ingresos se adhiere a los l&iacute;mites legales y est&aacute; permitido a nivel mundial. Nuestro compromiso con la transparencia y las operaciones &eacute;ticas garantiza servicios publicitarios confiables y eficientes para nuestros valiosos usuarios.</p>
                        <p><strong>Exposici&oacute;n Equitativa para Anunciantes:</strong></p>
                        <p>Independientemente del tama&ntilde;o del paquete publicitario, todos los anunciantes tienen igual oportunidad de que se muestren sus anuncios. La selecci&oacute;n de contenido es aleatoria, asegurando equidad. M&uacute;ltiples paquetes proporcionan una mayor visibilidad seg&uacute;n las exposiciones disponibles.</p>
                        <p><strong>Evoluci&oacute;n de la Publicidad:</strong></p>
                        <p>En la era digital, la publicidad se ha convertido en una herramienta poderosa que ofrece oportunidades de ingresos sustanciales y perspectivas financieras sostenibles.</p>
                        <p><strong>Experiencia y Soporte de CyberGroupOn.com:</strong></p>
                        <p>Navegar por las complejidades de la publicidad puede ser desafiante, y aqu&iacute; es donde profesionales como CyberGroupOn.com entran en juego. Con su experiencia y conocimiento, pueden aliviar la carga y las complejidades asociadas con las campa&ntilde;as publicitarias. Confiar en ellos le permite centrarse en otros aspectos de su negocio mientras asegura que sus esfuerzos publicitarios est&eacute;n optimizados para el &eacute;xito.</p>
                        <p><strong>An&aacute;lisis de Datos e Informaci&oacute;n:</strong></p>
                        <p>El an&aacute;lisis de datos es crucial para una publicidad efectiva. Al aprovechar el poder de los datos, puede obtener valiosas ideas sobre el rendimiento de sus anuncios. El seguimiento de los indicadores clave de rendimiento proporciona informaci&oacute;n accionable para perfeccionar sus estrategias. CyberGroupOn.com puede ayudar en el an&aacute;lisis de estos datos, permiti&eacute;ndole tomar decisiones informadas y maximizar la efectividad de sus esfuerzos publicitarios.</p>
                        <p><strong>Conclusi&oacute;n</strong></p>
                        <p>En conclusi&oacute;n, adquirir la comprensi&oacute;n y las t&eacute;cnicas necesarias para aprovechar el poder de la publicidad desbloquea un mundo de potencial para generar ingresos y establecer oportunidades financieras sostenibles. Con el apoyo de profesionales como CyberGroupOn.com, que pueden manejar las complejidades de la publicidad, puede centrarse en su negocio mientras aprovecha los beneficios de una campa&ntilde;a publicitaria bien ejecutada. Aproveche las oportunidades que ofrece la publicidad y permita que CyberGroupOn.com haga el trabajo pesado por usted.</p>
                        <p>Al usar CyberGroupOn.com, acepta cumplir con estos t&eacute;rminos y condiciones. Nos reservamos el derecho de modificar estos t&eacute;rminos, y es su responsabilidad estar informado sobre cualquier cambio. El uso continuo significa la aceptaci&oacute;n de los t&eacute;rminos modificados.</p>
                        <p><strong>Propiedad Intelectual y Cumplimiento de Contenido:</strong></p>
                        <p>Se proh&iacute;be estrictamente a los usuarios promover actividades relacionadas con drogas, violencia, trafico ilegal, im&aacute;genes inapropiadas o contenido sexual dentro de las campa&ntilde;as publicitarias en CyberGroupOn.com. Cualquier violaci&oacute;n de esta pol&iacute;tica resultar&aacute; en la terminaci&oacute;n inmediata de su membres&iacute;a. Adem&aacute;s, cualquier acci&oacute;n que enga&ntilde;e o interrumpa los servicios proporcionados por CyberGroupOn.com llevar&aacute; a la terminaci&oacute;n inmediata de su membres&iacute;a, junto con la p&eacute;rdida de comisiones y bonificaciones asociadas. Es importante tener en cuenta que participar en tales actividades tambi&eacute;n puede resultar en cargos legales y/o criminales contra usted.</p>
                        <p><strong>Pol&iacute;tica Antispam:</strong></p>
                        <p>CyberGroupOn.com aplica una estricta pol&iacute;tica antispam y mantiene un enfoque de tolerancia cero hacia las actividades de spam. Cualquier miembro que se encuentre participando en actividades de spam enfrentar&aacute; la terminaci&oacute;n inmediata de su membres&iacute;a, lo que conllevar&aacute; a la p&eacute;rdida de bonificaci&oacute;n impagas, si las hubiera. Animamos a todos los miembros a participar en pr&aacute;cticas de marketing &eacute;ticas y responsables.</p>
                        <p><strong>Compra no reembolsable:</strong></p>
                        <p>Todas las compras realizadas en CyberGroupOn.com son estrictamente no reembolsables. CyberGroupOn.com no puede emitir reembolsos. Se anima a los usuarios a realizar compras con pleno conocimiento de esta pol&iacute;tica.</p>
                        <p><strong>Generaci&oacute;n de Ingresos y Programa de Referidos:</strong></p>
                        <p>Los usuarios en CyberGroupOn.com tienen la oportunidad de generar ingresos basados en sus actividades de venta. Los ingresos ganados dependen de la intensidad de estas actividades. Los usuarios recibir&aacute;n comisi&oacute;n del monto pagado por sus clientes, aplican t&eacute;rminos y condiciones. Esta plataforma proporciona una oportunidad &uacute;nica para el crecimiento econ&oacute;mico, incentivando la participaci&oacute;n activa.</p>
                        <p><strong>Derecho a Modificar T&eacute;rminos y Condiciones:</strong></p>
                        <p>Como proveedor de la plataforma, CyberGroupOn.com se reserva el derecho de realizar cambios en los t&eacute;rminos y condiciones que rigen el uso de la plataforma en cualquier momento durante su vida operativa. Estos cambios pueden incluir modificaciones a las reglas de uso, pol&iacute;ticas de privacidad, acuerdos de usuario y otras condiciones establecidas por CyberGroupOn.com. Notificaremos a los usuarios sobre cambios significativos para garantizar la transparencia. Ignorar o no revisar los t&eacute;rminos y condiciones no exime a los participantes del incumplimiento de estos. Cada usuario es responsable de revisar estos t&eacute;rminos y condiciones.</p>
                        <p><strong>Responsabilidad del Usuario y Aceptaci&oacute;n de Cambios:</strong></p>
                        <p>Los usuarios tienen la responsabilidad de mantenerse informados sobre cualquier cambio en los t&eacute;rminos y condiciones. Esto implica revisar peri&oacute;dicamente los t&eacute;rminos y condiciones para actualizaciones. Se recomienda que los usuarios verifiquen las modificaciones regularmente para asegurarse de estar al tanto de sus derechos y obligaciones al utilizar la plataforma. Al permanecer informados, los usuarios pueden tomar decisiones informadas de acuerdo con las pol&iacute;ticas actualizadas.</p>
                        <p><strong>El Uso Continuo Significa Aceptaci&oacute;n:</strong></p>
                        <p>El uso continuo de la plataforma despu&eacute;s de cualquier cambio significa la aceptaci&oacute;n de los t&eacute;rminos y condiciones modificados aun si no se han le&iacute;do los t&eacute;rminos y condiciones. Si un usuario no est&aacute; de acuerdo con los t&eacute;rminos y condiciones actualizados, se recomienda dejar de usar la plataforma de inmediato. Esta pol&iacute;tica garantiza que los usuarios est&eacute;n al tanto de sus responsabilidades y derechos en curso al interactuar con CyberGroupOn.com.</p>
                        <p><strong>Aviso sobre la Ubicaci&oacute;n en la L&iacute;nea:</strong></p>
                        <p>Las modificaciones a la ubicaci&oacute;n en la l&iacute;nea est&aacute;n estrictamente prohibidas. Es imperativo considerar cuidadosamente la ubicaci&oacute;n de su promotor de venta, ya que esta decisi&oacute;n es Definitivo Irrevocable</p>
                        <p><strong>Pol&iacute;tica de Modificaci&oacute;n de Cuentas:</strong></p>
                        <p>La recuperaci&oacute;n de cuentas asociadas con direcciones de correo electr&oacute;nico diferentes a la inicialmente registrada estar&aacute; sujeta a escrutinio y se otorgar&aacute; excepcionalmente despu&eacute;s de completar m&uacute;ltiples evaluaciones y ex&aacute;menes rigurosos. Se aclara expresamente que la plataforma no est&aacute; legalmente obligada a acceder a tales solicitudes de alteraciones.</p>
                        <p><strong>Protocolo de Seguridad de la Cuenta:</strong></p>
                        <p>Se aplica el uso de &ldquo;contrase&ntilde;as encriptadas.&rdquo; Ni CyberGroupOn.com ni su personal tienen acceso a las contrase&ntilde;as de los individuos afiliados. En consecuencia, la responsabilidad de mantener la seguridad de las cuentas recae expl&iacute;citamente en el usuario y/o el originador de la cuenta. Se proh&iacute;be estrictamente el uso de direcciones de correo electr&oacute;nico falsas. El incumplimiento de esta estipulaci&oacute;n pondr&aacute; en peligro su cuenta, dificultando las modificaciones de su contrase&ntilde;a. Se enfatiza que CyberGroupOn.com y su equipo de programadores no pueden alterar su contrase&ntilde;a en ning&uacute;n momento.</p>
                        <p><span style="color: #ff0000;"><strong>Descargo de Responsabilidad Legal:</strong></span></p>
                        <p><span style="color: #ff0000;"><strong>Cybergrupon.com declina de manera expl&iacute;cita cualquier conexi&oacute;n, respaldo o parte de asuntos relacionados con t&eacute;rminos raciales, sexuales, pol&iacute;ticos y religiosos. Las presentaciones realizadas por los presentadores son manifestaciones individuales &uacute;nicas y quedan fuera del &aacute;mbito de la representaci&oacute;n oficial de Cybergrupon.com. La plataforma no fomenta ni respalda actividades vinculadas a estos t&eacute;rminos, y la participaci&oacute;n en tales asuntos recae &uacute;nicamente en la responsabilidad del usuario como entidad independiente. Asimismo, se establece que el presentador ser&aacute; responsable de sus propias acciones y expresiones durante las presentaciones realizadas en caso de hace promoci&oacute;n online o reuniones virtuales.</strong></span></p>
                    </div>


                </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              </div>
          </div>
      </div>
  </div>
